name: Test Tag creation
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  build:
    name: Tag creation
    env:
      APP_NAME: "Smartlets"
      APP_VERSION: "v1.0.0-debug"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Tag and prepare release
        id: tag_and_prepare_release
        uses: K-Phoen/semver-release-action@master
        with:
          tag: ${{ env.APP_VERSION }}
          release_branch: dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release notes
        if: steps.tag_and_prepare_release.outputs.tag
        uses: Roang-zero1/github-create-release-action@master
        with:
          created_tag: ${{ steps.tag_and_prepare_release.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a Debug APK
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.APP_VERSION }}${{ GITHUB_RUN_NUMBER }}
          artifacts: "build/app/outputs/apk/debug/*.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
